import assert from 'node:assert/strict';
import test from 'node:test';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as worker from '../../src/worker/src/index.js';

const schema = readFileSync(fileURLToPath(new URL('../../src/worker/schema.sql', import.meta.url)), 'utf8');
const appSource = readFileSync(fileURLToPath(new URL('../../src/worker/assets/app.js', import.meta.url)), 'utf8');
class D1Statement { constructor(db, sql) { this.db = db; this.sql = sql; this.values = []; } bind(...values) { this.values = values; return this; } first() { return this.db.prepare(this.sql).get(...this.values) || null; } all() { return { results: this.db.prepare(this.sql).all(...this.values) }; } }
class D1Database { constructor(db) { this.db = db; } prepare(sql) { return new D1Statement(this.db, sql); } batch(statements) { this.db.exec('BEGIN IMMEDIATE'); try { const out = statements.map(statement => { const result = this.db.prepare(statement.sql).run(...statement.values); return { meta: { changes: Number(result.changes) } }; }); this.db.exec('COMMIT'); return Promise.resolve(out); } catch (error) { this.db.exec('ROLLBACK'); return Promise.reject(error); } } }
function fixture() { const db = new DatabaseSync(':memory:'); db.exec('PRAGMA foreign_keys=ON;'); db.exec(schema); db.prepare('INSERT INTO app_users(uid,role,active,run_marker) VALUES (?,?,1,?)').run('uid-one','person_1','uat'); db.prepare('INSERT INTO app_users(uid,role,active,run_marker) VALUES (?,?,1,?)').run('uid-two','person_2','uat'); return { db, env: { DB: new D1Database(db), RUN_MARKER: 'uat' } }; }
async function setup(env, tag, confirmedAt = '2026-08-10T10:00:00.000Z') { await worker.createCatalogValue(env,'uid-one',tag+'-country','country',{ value_key: tag+'-sa', label:'السعودية' }); const customer = await worker.createCustomer(env,'uid-one',tag+'-customer',{ name:'عميل '+tag, country:tag+'-sa' }); const work = await worker.createWork(env,'uid-one',tag+'-work',{ customer_id:customer.id,title:'عمل '+tag,country:tag+'-sa',confirmed_at:confirmedAt }); const priceReq = await worker.createPriceChangeRequest(env,'uid-one',tag+'-price',work.id,{ version:work.version,movement_type:'BASE',amount_riyals:'1000.00',reason:'base' }); await worker.approvePriceChangeRequest(env,'uid-two',tag+'-price-approve',work.id,priceReq.id); return worker.getWork(env, work.id); }

test('UAT-043 waits for initial auth restoration and account admin UI does not target raw uid', () => {
  assert.match(appSource, /function waitForInitialUser()/);
  assert.match(appSource, /await adapter.waitForInitialUser?.()/);
  assert.doesNotMatch(appSource, /account-email-form[^>]+data-uid/);
  assert.doesNotMatch(appSource, /account-reset-form[^>]+data-uid/);
});

test('UAT-047 reversal approval survives unrelated work-version drift', async () => {
  const { db, env } = fixture(); try { let work = await setup(env,'drift','2026-09-10T10:00:00.000Z'); await worker.createClientPayment(env,'uid-one','drift-payment',work.id,{ version:work.version,amount_riyals:'100.00',effective_at:'2026-09-12T10:00:00.000Z',payment_method:'BANK_TRANSFER' }); work = await worker.getWork(env,work.id); const payment = (await worker.listClientPayments(env,work.id))[0]; const req = await worker.createPaymentReversalRequest(env,'uid-one','drift-reversal-request',work.id,{ version:work.version,payment_id:payment.id,reason:'correct' }); work = await worker.getWork(env,work.id); await worker.changeWorkTitle(env,'uid-one','drift-title',work.id,{ version:work.version,new_title:'عنوان جديد',reason:'unrelated change' }); const result = await worker.approvePaymentReversalRequest(env,'uid-two','drift-reversal-approve',work.id,req.id); assert.equal(result.request.state,'APPROVED'); assert.equal(result.financials.approved_payments_total_halalas,0); assert.equal(db.prepare("SELECT COUNT(*) AS count FROM payment_reversals").get().count,1); } finally { db.close(); }
});

test('D-024 preserves closed snapshot and carries cancellation plus later reversal adjustments append-only', async () => {
  const { db, env } = fixture(); try { let work = await setup(env,'cancel'); await worker.createClientPayment(env,'uid-one','cancel-payment',work.id,{ version:work.version,amount_riyals:'400.00',effective_at:'2026-08-12T10:00:00.000Z',payment_method:'BANK_TRANSFER',received_by:'uid-one' }); await worker.closeSettlement(env,'uid-one','cancel-close','2026-08',{}); const beforeSnapshots = await worker.listSettlementSnapshots(env,'2026-08'); assert.equal(beforeSnapshots.length,1); work = await worker.getWork(env,work.id); const cancelReq = await worker.createCancelArchiveRequest(env,'uid-one','cancel-request',work.id,{ version:work.version,action:'CANCEL',target_execution_status:'PARTIALLY_STOPPED',reason:'cancel' }); const cancelled = await worker.approveCancelArchiveRequest(env,'uid-two','cancel-approve',work.id,cancelReq.id); assert.equal(cancelled.work.status,'PARTIALLY_STOPPED'); const afterSnapshots = await worker.listSettlementSnapshots(env,'2026-08'); assert.deepEqual(afterSnapshots,beforeSnapshots); let adjustments = await worker.listSettlementAdjustments(env); assert.equal(adjustments.length,1); assert.equal(adjustments[0].adjustment_type,'CANCELLATION'); assert.equal(adjustments[0].person_2_delta_halalas,12000-Number(beforeSnapshots[0].person_2_work_share_halalas)); const fin = await worker.getWorkFinancials(env,work.id); assert.equal(fin.customer_remaining_halalas,60000); assert.equal(fin.collection_status,'PARTIALLY_COLLECTED'); assert.equal(fin.internal_share_basis_halalas,40000); work = await worker.getWork(env,work.id); const payment = (await worker.listClientPayments(env,work.id))[0]; const reverseReq = await worker.createPaymentReversalRequest(env,'uid-one','cancel-reversal-request',work.id,{ version:work.version,payment_id:payment.id,reason:'historical correction' }); const reversal = await worker.approvePaymentReversalRequest(env,'uid-two','cancel-reversal-approve',work.id,reverseReq.id); assert.equal(reversal.request.state,'APPROVED'); assert.equal(reversal.financials.customer_remaining_halalas,100000); assert.equal(reversal.financials.collection_status,'UNPAID'); adjustments = await worker.listSettlementAdjustments(env); assert.equal(adjustments.length,2); assert.equal(adjustments[1].adjustment_type,'POST_CANCEL_REVERSAL'); assert.equal(adjustments[1].person_2_delta_halalas,-12000); const period = adjustments[0].period_key; assert.equal(adjustments[1].period_key,period); const preview = await worker.getSettlementPreview(env,period,{}); assert.equal(preview.settlement_adjustment_person_2_halalas,-Number(beforeSnapshots[0].person_2_work_share_halalas)); assert.equal((await worker.listSettlementSnapshots(env,'2026-08')).length,1); assert.throws(() => db.exec('DELETE FROM settlement_adjustments'),/append only/); } finally { db.close(); }
});
